name: Create tag automatically

on:
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    # permissions:
    #   contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Create tag and push to repo
        run: |
          npx -y monotag@latest tag-push

