name: pr-build

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    name: Build PRs
    uses: flaviostutz/gh-makefile/.github/workflows/make-ci.yml@main
    with:
      working-directory: ./
      tooling: node
      tooling-version: 16
      target-build: true
      target-lint: true
      target-unit-tests: true
